export const AI_ERROR_CODES = {
  AI_READ_ONLY: 'AI_READ_ONLY',
  BACKEND_OPERATION_FAILED: 'BACKEND_OPERATION_FAILED',
  CAPABILITY_DISABLED: 'CAPABILITY_DISABLED',
  CATALOG_ITEM_NOT_FOUND: 'CATALOG_ITEM_NOT_FOUND',
  CATALOG_OPERATION_FAILED: 'CATALOG_OPERATION_FAILED',
  CLOSE_USER_CONNECTION_DENIED: 'CLOSE_USER_CONNECTION_DENIED',
  CONFIG_BUSY: 'CONFIG_BUSY',
  CONFIG_CONFLICT: 'CONFIG_CONFLICT',
  CONFIG_DOMAIN_NOT_FOUND: 'CONFIG_DOMAIN_NOT_FOUND',
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_INVALID_PATCH: 'CONFIG_INVALID_PATCH',
  CONFIG_REVISION_CONFLICT: 'CONFIG_REVISION_CONFLICT',
  CONFIG_SCOPE_DENIED: 'CONFIG_SCOPE_DENIED',
  CONFIG_TARGET_REQUIRED: 'CONFIG_TARGET_REQUIRED',
  CONFIG_WRITE_FAILED: 'CONFIG_WRITE_FAILED',
  CONNECTION_TYPE_NOT_EXPOSED: 'CONNECTION_TYPE_NOT_EXPOSED',
  DEADLINE_EXCEEDED: 'DEADLINE_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_PARAMS: 'INVALID_PARAMS',
  LOG_READ_FAILED: 'LOG_READ_FAILED',
  MCP_DISABLED: 'MCP_DISABLED',
  PORT_NOT_FOUND: 'PORT_NOT_FOUND',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
  RESOURCE_LIMIT: 'RESOURCE_LIMIT',
  RESULT_TOO_LARGE: 'RESULT_TOO_LARGE',
  SCHEDULER_STOPPED: 'SCHEDULER_STOPPED',
  SESSION_ALREADY_EXISTS: 'SESSION_ALREADY_EXISTS',
  SESSION_CLOSED: 'SESSION_CLOSED',
  SESSION_CLOSED_DURING_START: 'SESSION_CLOSED_DURING_START',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_STOPPED_DURING_START: 'SESSION_STOPPED_DURING_START',
  SESSION_WRITE_LEASE_REQUIRED: 'SESSION_WRITE_LEASE_REQUIRED',
  SESSION_WRITE_LOCKED: 'SESSION_WRITE_LOCKED'
} as const

export type AiErrorCode = (typeof AI_ERROR_CODES)[keyof typeof AI_ERROR_CODES]

export const COMMON_AI_ERROR_CODES: AiErrorCode[] = [
  AI_ERROR_CODES.MCP_DISABLED,
  AI_ERROR_CODES.CAPABILITY_DISABLED,
  AI_ERROR_CODES.REQUEST_CANCELLED,
  AI_ERROR_CODES.DEADLINE_EXCEEDED,
  AI_ERROR_CODES.INTERNAL_ERROR
]
